### ISSUE TITLE
Unable to Query FreeIPA LDAP

### ISSUE THREAD

**Issue by 0xa51f** [PetzJohannes/ldap2zabbix#1]
Hi

I am getting the following error whilst trying to sync with FreeIPA:

sudo python3 ldap2zabbix.py -v
INFO:pyzabbix:JSON-RPC Server Endpoint: http://zabbix.domain.net/zabbix/api_jsonrpc.php
INFO:pyzabbix:Zabbix API version is: 5.4.3
Traceback (most recent call last):
  File "ldap2zabbix.py", line 118, in <module>
    if username not in users:
TypeError: unhashable type: 'list'

I had to ammend ldap2zabbix.py line 115 to:

            username = ldapUser['uid']

since  sAMAccountName is obsolete in IPA3, see https://www.freeipa.org/page/Obsolete:IPAv3_User_Attribute_Mapping

my config file is:

zabbix:
  url: http://zabbix.domain.net/zabbix
  user: Admin
  password: zabbix
  default-role: ldap-user-role
  disabled-group: disabled-ldap-users

ldap:
  uri: ldap://ldapserveraddress:389
  bindUser: uid=admin,cn=users,cn=accounts,dc=domain,dc=net
  bindPassword: !password
  objectGroup: groupofnames
  objectUser: person
  attributeMember: member
  attributeLastName: sn
  attributeFirstName: givenName
  attributeUsername: uid

groups:
  - name: "user-group-from-ldap"
    dn: cn=ipausers,cn=groups,cn=accounts,dc=domain,dc=net
    role: 'ldap-user-role'
    permissions:
      - group: Linux servers
        permission: read-only

please let me know if you can assist

Thanks

**Comment by PetzJohannes** [comment]
Hi,

maybe the `ldapUser['uid']` is not a string so it will fail to search a list in the `users` dict.

**Comment by 0xa51f** [comment]
Thanks for your suggestion, but it's not that. 

I have taken an alternate route to achieve sync between Zabbix and LDAP now, so will close this
