### ISSUE TITLE
LDAP Surfer required

### ISSUE THREAD

**Issue by nod0n** [PetzJohannes/ldap2zabbix#2]
Is [LDAP Surfer really](https://github.com/PetzJohannes/ldap2zabbix/blob/master/README.md?plain=1#L27) required and and what is it?

**Comment by PetzJohannes** [comment]
The LDAP Surfer is required. It is a service account in your LDAP / Active Directory. It will be used to query your LDAP users.

Some LDAP servers do not need service accounts to query them. But this case is not supported. Anyway you can use a service account for this.
